version: '3.8'
services:
  omop_database:
    build: omop_database
    environment:
      - POSTGRES_PASSWORD=testme
      - POSTGRES_DB=omop
      - POSTGRES_USER=postgres
    ports:
      - 15432:5432
  webapi_database:
    build: webapi_database
    environment:
      - POSTGRES_PASSWORD=testme
    ports:
      - 25432:5432
  webapi:
    build: webapi
    ports:
      - 8080:8080
    depends_on:
      - webapi_database
      - omop_database
  atlas:
    build: atlas
    ports:
      - 3000:3000
    depends_on:
      - webapi